---
title: "ROMOP Readme"
author: "Benjamin S. Glicksberg"
date: "5/30/2018"
output:
  html_document:
    toc: yes
    toc_depth: 4
  pdf_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ROMOP

ROMOP is a flexible R package to interface with the [Observational Health Data Sciences and Informatics (OHDSI)](https://www.ohdsi.org/) [OMOP Common Data Model](https://www.ohdsi.org/data-standardization/). Briefly, OMOP is a standardized relational database schema for Electronic Health Record (EHR) or Electronic Medical Record (EMR) data (i.e., patient data collected during clinical visits to a health system). The main benefit of a standardized schema is that it allows for interoperability between institutions, even if the underlying EHR vendors are disparate.

For a detailed description of the OMOP common data model, please visit this [helpful wiki](https://github.com/OHDSI/CommonDataModel/wiki).

In its backend, OMOP relies on standardized data ontologies and metathesaureses, such as the [Unified Medical Language System (UMLS)](https://www.nlm.nih.gov/research/umls/), and as such, the queries within ROMOP heavily rely on these vocabularies. [Athena](http://athena.ohdsi.org/) is a great tool to better understand the concepts in these ontologies and identify ideal search terms of interest.

[Manuscript Information]

[SERVER & COMPUTATIONAL POWER INFO FOR TIME-RELATED OUTPUT]


## Requirements

#### Clinical Data

ROMOP requires EHR data to be in OMOP format and on a server accessible to by the user. In it's current form, ROMOP requires the database to be in either _MySQL_ or _PostgreSQL_ format, but subsequent releases will allow for other formats.

#### Programming Language

ROMOP is built in the R environment and developed on version 3.4.4 (2018-03-15).  

ROMOP requires the following R packages:

* [odbc](https://cran.r-project.org/web/packages/odbc/index.html) (developed on version 1.1.5)
* [DBI](https://cran.r-project.org/web/packages/DBI/index.html) (developed on version 1.0.0)
* [data.table](https://cran.r-project.org/web/packages/data.table/data.table.pdf) (developed on version 1.10.4-3).
* [dplyr](https://dplyr.tidyverse.org/) (developed on version 0.7.4).

Driver-specific (i.e., one or the other): 

* [RMySQL](https://cran.r-project.org/web/packages/RMySQL/index.html) (developed on version 0.10.14).
* [PostgreSQL](https://cran.r-project.org/web/packages/RPostgreSQL/index.html)

## Installation

### Download

ROMOP can be installed easily from github using the [devtools](https://cran.r-project.org/web/packages/devtools/index.html) package:

```
library(devtools)
install_github("BenGlicksberg/ROMOP")
```
  
Alternatively, the package can be downloaded directly from the [github page](https://github.com/BenGlicksberg/ROMOP) and installed by the following steps:

1. Unzip ROMOP-master.zip
2. R CMD build ROMOP-master
3. R CMD INSTALL ROMOP_0.1.0.tar.gz

Please see the [Setup](#setup) section to properly configure the package to work.
  
&nbsp;

### Setup

#### Credentials

In accordance with best practices for storing sensitive information, credentials are not saved in plain text but in the .Renviron file. A formatted .Renviron file is provided with the package with the following fields to fill in:

```
driver = ""
host = ""
username = ""
password = ""
dbname = ""
port = "3306" 

```

* driver: "MySQL" or "PostgreSQL"
* dbname: OMOP EHR database name  
  
Note that this .Renviron file has to be in the same directory where R is launched. If already using an .Renviron file, add this information to it.
  
#### Checks

With credentials correctly configured, the package can be loaded. ROMOP will now check for 3 conditions to be met:

1. Check that the credentials exist and can be retrieved from .Renviron file:  
  _requires driver, host, username, password, dbname, and port != ""_
  
2. Check that connection to OMOP EHR server and database can be made:  
  _uses the above credentails_
  
3. Check to ensure all required OMOP tables exist and contain (any) data:  
  _the required tables are:_  
```
"concept","concept_ancestor","concept_relationship","condition_occurrence","death","device_exposure","drug_exposure","measurement","observation","person","procedure_occurrence","visit_occurrence"
```

* if any of the above tables are missing, a warning message will be produced and the package will not be able to load properly.
* if any of the above tables exist, but do not contain any data, a warning message will be produced but the package will still be able to function.
  
#### On start
  
Successfully pasing all checks will allow the user to begin using ROMOP.  

1. Set an output directory to use with the [changeOutDirectory](#changeoutdirectory) fucntion (note: the default output directory will be decalred on package load).   
2. Create/load the Data ontology (required to decode data types) using the [makeDataOntology](#makedataontology). For the first time running this package, the concept ontology will have to first be built, but if the store_ontology option is selected, the onotlogy will be saved as an .rds file for subsequent loading. 

&nbsp;


## Functions
  
### Utility
  
#### getDemographics
  
*Description*:&nbsp;&nbsp;Retrieves and formats patient demographic data from the __person__ and __death__ tables. Option to restrict to patientlist of interest.  
  
*Useage*:&nbsp;&nbsp;ptDemo <- getDemographics(patient_list=NULL,declare=TRUE)  
  
*Arguments*:  
  
&nbsp;&nbsp;patient_list&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _comma-separated string of patient ids_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a provdied patientlist will restrict search to ids. NULL will return demographic data for all available patients  
  
&nbsp;&nbsp;declare&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _TRUE/FALSE_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if TRUE, outputs status and updates to the screen  
  
*Value*:  
  
&nbsp;&nbsp;Returns a data.table with demographic data: person_id, birth_datetime, age, Gender, Race, Ethnicity, death_date, Status (Alive/Deceased)  
  
*Details*: 

* patient_list should be in the following format: "patient_id_1, patient_id_2, ..."  
  
&nbsp;    

#### getEncounters

*Description*:&nbsp;&nbsp;Retrieves and formats patient encounter data from the __visit_occurrence__ table. Requires patientlist input.  
  
*Useage*:&nbsp;&nbsp;ptEncs <- getEncounters(patient_list,declare=TRUE)  
  
*Arguments*:  
  
&nbsp;&nbsp;patient_list&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _comma-separated string of patient ids_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; searches for all encounter data for the patientlist inout.  
  
&nbsp;&nbsp;declare&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _TRUE/FALSE_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if TRUE, outputs status and updates to the screen
  
*Value*:  
  
&nbsp;&nbsp;Returns a data.table with encounter data:  person_id, visit_occurrence_id, visit_start_datetime, visit_end_datetime, visit_source_value, visit_concept, visit_source_concept, admitting_concept, discharge_concept 
  
*Details*: 

* patient_list should be in the following format: "patient_id_1, patient_id_2, ..."  
  
&nbsp;    

#### getClinicalData 

*Description*:&nbsp;&nbsp;Retrieves all relevant clinical data for individuals in a patientlist. Wrapper for domain-specific getData functions (which can also be used separately).
  
*Useage*:&nbsp;&nbsp;ptClinicalData <- getClinicalData(patient_list, declare=TRUE) 
  
*Arguments*:  
  
&nbsp;&nbsp;patient_list&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _comma-separated string of patient ids_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a provdied patientlist will restrict search to ids. NULL will return demographic data for all available patients  
  
&nbsp;&nbsp;declare&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _TRUE/FALSE_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if TRUE, outputs status and updates to the screen  
   
*Value*:  
&nbsp;&nbsp;Returns a list of data.tables stratified by domain type (e.g., ptClinicalData\$Concept, ptClinicalData\$Observation, etc...)  
  
*Details*:  
  
* patient_list should be in the following format: "patient_id_1, patient_id_2, ..."    
* getClinicalData calls domain-specific getData functions for the following domains: Observation, Condition, Procedure, Medication (Drug), Measurement, and Device. Each function can also be run individually (e.g, getConditions; getMedications).  
* In addition to datetimes, visit_occurrence_ids, <domain>_concept_ids and <domain>_source_concept_ids, other domain-specific concepts and values are retrieved and mapped:  
    + Observation: observation_type_concept, value_as_number, value_as_string, value_as_concept, unit_source_value  
    + Condition: condition_type_concept, condition_status  
    + Procedure: procedure_type_concept, quantity,   
    + Medication: drug_type_concept, stop_reason, refills, quantity, days_supply, sig, route_concept, effective_drug_dose, dose_unit_concept, route_source_value, frequency, frequency_unit, rx_quantity_unit_source_value  
    + Measurement: measurement_type_concept, value_as_number, value_as_concept, unit_concept
    + Device: device_type_concept  
  
&nbsp;  

#### findPatients 

*Description*:&nbsp;&nbsp;Main function to identify patients based on clinical data inclusion (and exclusion, if desired) criteria. Flexible to allow for multiple data types, vocabularies, and concepts.  
  
*Useage*:&nbsp;&nbsp;  patientlist <- findPatients(strategy_in="mapped", vocabulary_in, codes_in, function_in = "or", strategy_out = NULL, vocabulary_out = NULL, codes_out = NULL, function_out = NULL, declare=FALSE, save=FALSE, out_name=NULL)  
  
*Arguments*:  
  
&nbsp;&nbsp;strategy_in&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _mapped_ or _direct_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; dictates the strategy for how inclusion criteria are treated (see Details).
  
&nbsp;&nbsp;vocabulary_in&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _vocabularies for inclusion criteria_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; comma-separated string of relevant vocabularies for inclusion criteria (see Details).  
   
&nbsp;&nbsp;codes_in&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _specific concept codes for inclusion criteria_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; semi-colon separated string of code concepts for inclusion criteria, corresponding to the order for vocabulary_in. Multiple codes can be used per vocabulary and should be comma-separated (see Details).  
  
&nbsp;&nbsp;function_in&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _and_ or _or_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; dictates how multiple inclusion should be treated. _and_ necessitates that all inclusion criteria are met (i.e., intersection), while _or_ allows for any critera to be met (i.e., union) (see Details).   
  
&nbsp;&nbsp;strategy_out&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _mapped_ or _direct_ or NULL (default)  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; dictates the strategy for how exclusion are treated. NULL indicates no exclusion criteria.
  
&nbsp;&nbsp;vocabulary_out&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _vocabularies for exclusion criteria_ or NULL (default)   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; comma-separated string of relevant vocabularies for exclusion criteria. NULL indicates no exclusion criteria.  
   
&nbsp;&nbsp;codes_our&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _specific concept codes for exclusion criteria_ or NULL (default)  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; semi-colon separated string of code concepts for inclusion criteria, corresponding to the order for vocabulary_out. Multiple codes can be used per vocabulary and should be comma-separated. NULL indicates no exclusion criteria.  
  
&nbsp;&nbsp;function_out&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _and_ or _or_ or NULL  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; dictates how multiple exclusion should be treated. _and_ necessitates that all exclusion criteria are met (i.e., intersection), while _or_ allows for any critera to be met (i.e., union). NULL indicates no exclusion criteria.  

&nbsp;&nbsp;declare&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _TRUE/FALSE_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if TRUE, outputs status and updates to the screen.  

&nbsp;&nbsp;save&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _TRUE/FALSE_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if TRUE, various query output saved to outDirectory (see Details).  

&nbsp;&nbsp;out_name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _name assigned to search query_ or NULL  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if save == TRUE, saves query using provided name. If the provided name already exists as a directory (or is NULL), the directory defaults to datetime name (see Details).  
   
*Value*:  
&nbsp;&nbsp;Returns a list of patients that meet inclusion criteria (and not exclusion criteria if entered).   
  
*Details*:  
  
* _direct_ strategy queries the concepts directly by _source_concept in clinical tables. _mapped_ maps to common ontology (via __concept_synonym__) and identifies relevant descendants (via __concept_ancestor__) to search for in _concept fields. 
* the [exploreConcepts](#exploreconcepts) function can be used to find ideal concepts to search for.  
* vocabulary_ input for multiple inputs should use relevant vocabularies (see [showDataTypes](#showdatatypes) ) as a comma-separated string, e.g., "ATC, ICD10CM, SNOMED".
* codes_ input correspond to the order as the vocabulary_ input and should be semi-comma separated string in the same order as above. Multiple terms per vocabulary type should be comma-separated. e.g., "A01A; K50, K51; 235599003" correspond to "A01A" for ATC, "K50" and "K51" for ICD10CM, and "235599003" for SNOMED.    
* function_ corresponds to how criteria should be treated. _and_ necessitates patients meet all criteria while _or_ allows for patients to meet any of the criteria.   
* if save == TRUE, the following information is saved in a directory per query:  
    + query: all arguments for the search.
    + _criteria_mapped: all original criteria for inclusion (and exclusion if applicable) that are mapped to dataOntology.
    + criteria_mapped_concepts: all mapped concepts used for inclusion (and exclusion if applicable) that are used to search in clinical data tables. Additionally, the pt_count column displays the number of unique patients that have a record with the corresponding concept.  
    + outcome: results of the search (most relevant when exclusion criteria are applied).  
    + patient_list: list of patients that meet inclusion (and not exclusion, if applicable) criteria.
 
&nbsp;   

### Misc.
  
#### changeOutDirectory  

*Description*:&nbsp;&nbsp; Sets the current outDirectory which will store the Data Ontology and all function output. Option to create directory if does not exist.  
  
*Useage*:&nbsp;&nbsp;changeOutDirectory(outdir="path/to/directory", create=FALSE)  
  
*Arguments*:  
&nbsp;&nbsp;outdir&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; directory path  
  
&nbsp;&nbsp;create&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _TRUE/FALSE_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; will create the directory if it does not exist
  
*Value*:  
&nbsp;&nbsp; Nothing returned; simply sets (and creates if set to) output directory
  
*Details*:  

* If directory does not exist and create=FALSE, a warning message will appear and the output directory will not be changed.
  
&nbsp; 
  
#### makeDataOntology

*Description*:&nbsp;&nbsp;Creates general Data Ontology used by all data tables from the __concept__ table. Option to save/load.  
  
*Useage*:&nbsp;&nbsp;dataOntology <- makeDataOntology(declare=TRUE,store_ontology=FALSE)  
  
*Arguments*:  
&nbsp;&nbsp;declare&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  _TRUE/FALSE_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if TRUE, outputs status and updates to the screen  
  
&nbsp;&nbsp;store_ontology&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _TRUE/FALSE_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if TRUE, will save/load the ontology instead of active querying  
  
*Value*:  
&nbsp;&nbsp;Returns a data.table with concept data.  
  
*Details*:  

* Generating the Data Ontology takes ~31.2 secs and is ~491.6 Mb.  
* If declare == TRUE, the following information will be returned:  

```
Retrieving concept data...
Concept data loaded; data found for: 
## unique domains.
## unique vocabularies.
### unique concept classes.
```  
  
* If store_ontology == TRUE, attempts to load from memory (in the outDirectory) and saves if does not exist (~53 Mb). Loading takes ~8 secs.
  
&nbsp; 

#### summarizeDemographics


*Description*:&nbsp;&nbsp;Summarizes patient demographic data from the [getDemographics](#getdemographics) function.
  
*Useage*:&nbsp;&nbsp;summarizeDemographics(ptDemo)  
  
*Arguments*:  
  
&nbsp;&nbsp;ptDemo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _patient demographics table_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ptDemo is the patient demographics object from the getDemographics function output  
  
*Value*:  
  
&nbsp;&nbsp;N/A; outputs message with descriptive summary statistics for the relevant patient demographic data.  
  
&nbsp;  

#### showDataTypes 

*Description*:&nbsp;&nbsp;Details relevant vocabularies per domain. Requires dataOntology to have been created (via [makeDataOntology](#makedataontology)).
  
*Useage*:&nbsp;&nbsp;showDataTypes()  
  
*Arguments*:  
  
N/A
  
*Value*:  
  
&nbsp;&nbsp;Returns a table of vocabularies contained within clinical domains: Condition, Observation, Measurement, Device, Procedure, Drug.  

&nbsp; 
  
#### exploreConcepts 

*Description*:&nbsp;&nbsp;For given vocabulary and concept, returns the mapped standard concept(s) as well as decendent concept(s)
  
*Useage*:&nbsp;&nbsp;conceptsInfo <- exploreConcepts(vocabulary, codes) 
  
*Arguments*:  
  
&nbsp;&nbsp;vocabulary&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _vocabulariy_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; comma-separated string of relevant vocabularies for inclusion criteria (see Details).  
   
&nbsp;&nbsp;codes&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _concept codes_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; semi-colon separated string of code concepts for inclusion criteria, corresponding to the order for vocabulary. Multiple codes can be used per vocabulary and should be comma-separated (see Details).  
  
*Value*:  
  
&nbsp;&nbsp;Returns a table of concepts contained under (i.e., below in the heirarchy) the query concept.  
  
  *Details*:  

* vocabulary input for multiple inputs should use relevant vocabularies (see [showDataTypes](#showdatatypes) ) as a comma-separated string, e.g., "ATC, ICD10CM".
* codes input correspond to the order as the vocabulary input and should be semi-comma separated string in the same order as above. Multiple terms per vocabulary type should be comma-separated. e.g., "A01A; K50, K51" correspond to "A01A" for ATC and "K50" and "K51" for ICD10CM.   
  
&nbsp; 
  
## Examples
  Both simple and advanced [findPatients](#findpatients) queries will be outlined. See the [Output](#output) section for description of output if save == TRUE.  
  
### Simple


1. Disease category (ICD10CM): find all "Type 2 Diabetes Mellitus" patients (E11)   
  
  Here we will set a single inclusion criterion. The inclusion vocbulary is set to _ICD10CM_ and the inclusion code is _E11_ corresponding to the vocabulary. Because the inclusion strategy is set as "mapped", ROMOP will map the ICD10CM code to a common ontology (SNOMED) term and find all descendants to search for (see [Code Breakdown](#code-breakdown) for details on how this works).
  
  _query_
   
    patient_list = findPatients(strategy_in="mapped", vocabulary_in = "ICD10CM", codes_in = "E11")  
  
  _time_: 15.3 secs

  
&nbsp;  

2. Specific disease (ICD9CM): find all patients with "Diabetes with ketoacidosis, type I [juvenile type], not stated as uncontrolled" __only__ (250.11)  

  Here we will search for patients that have the specific _ICD9CM_ code _250.11_ __only__, i.e., not map to common ontology (see [Code Breakdown](#code-breakdown) for the importance of this distiction).  
  
  _query_
   
    patient_list = findPatients(strategy_in="direct", vocabulary_in = "ICD9CM", codes_in = "250.11")  
  
  _time_: 1.1 min

  
&nbsp; 

3. Multiple diseases (ICD10CM): find all patients with "Essential (primary) hypertension" (I10) __and__ "Angina pectoris with documented spasm" (I20.1)   

  Here we will search for patients that have the multiple ICD10CM codes. While we put a single inclusion vocabulary, we will put two inclusion codes separated by a comma. Also we set the inclusion function to "and" which requires __both__ criteria to be met.  
  
  _query_
   
    patient_list = findPatients(strategy_in="mapped", vocabulary_in = "ICD10CM", codes_in = "I10, I20.1", function_in = "and")  
  
  _time_: 23.8 secs

  
&nbsp; 

4. Drug class (ATC): find all patients prescribed with any "Serotonin receptor antagonists" (A03AE)     

  Here we will search for patients by drug ATC code. As the inclusion strategy is set to "mapped", all drugs that fall into this category will automatically be identified and searched for (see [Code Breakdown](#code-breakdown) for details on how this works).
  
  _query_
   
    patient_list = findPatients(strategy_in="mapped", vocabulary_in = "ATC", codes_in = "A03AE")  
  
  _time_: 1.1 secs

  
&nbsp; 

5. Disease category (ICD10CM) but not Drug (MeSH): find all patients with "Other anxiety disorders" (F31), but _not_ prescribed with "Clonazepam" (D002998)  

  Here we will search for patients by ICD10CM code as before. We also identify all patients prescribed with the MeSH term for "Clonazepam", which will be removed from the original list.  
  
  _query_
   
    patient_list = findPatients(strategy_in="mapped", vocabulary_in = "ICD10CM", codes_in = "F41", strategy_out="mapped", vocabulary_out = "MeSH", codes_out = "D002998", function_out = "and")  
  
  _time_: 16.5 secs

  
&nbsp; 

### Advanced

1. Multiple disease categories (ICD10CM) and lab test (LOINC) but not multiple disease categories (ICD10CM) nor drug class (RxNorm): find all patients with "Crohn's disease" (F31) and "Malignant neoplasm of prostate" (C61) with "CBC W Auto Differential panel - Blood" (57021-8), but _not_ "Gastroenteritis and colitis due to radiation" (K52.0) nor "Allergic and dietetic gastroenteritis and colitis" (K52.2) nor prescribed with any "Aminosalicylate" (113374)  

  Here we will search for patients by ICD10CM code as before. We also identify all patients prescribed with the MeSH term for "Clonazepam", which will be removed from the original list.  
  
  _query_
   
    vocabulary_in = "ICD10CM, LOINC"
    codes_in = "K50;C61, 57021-8" 
    vocabulary_out = "ICD10CM, RxNorm"
    codes_out = "K52.0; K52.2,  113374" 
   
    patient_list = findPatients(strategy_in="mapped", vocabulary_in = vocabulary_in, codes_in = codes_in, function_in = "and", strategy_out="mapped", vocabulary_out = vocabulary_out, codes_out = codes_out, function_out = "or")  
  
  _time_: 5.9 mins

  
&nbsp; 


## Output  

All output is saved in the output directory (use [changeOutDirectory](#changeoutdirectory) to set). Additionally, the data ontology file will be loaded from here and saved if set to using the makeDataOntology](#makedataontology) function.

If save==TRUE is selected for [findPatients](#findPatients) queries, various information will be saved in a created query-specific directory within the outDirectory:  
    + query: all arguments for the search.
    + _criteria_mapped: all original criteria for inclusion (and exclusion if applicable) that are mapped to dataOntology.
    + criteria_mapped_concepts: all mapped concepts used for inclusion (and exclusion if applicable) that are used to search in clinical data tables. Additionally, the pt_count column displays the number of unique patients that have a record with the corresponding concept.  
    + outcome: results of the search (most relevant when exclusion criteria are applied).  
    + patient_list: list of patients that meet inclusion (and not exclusion, if applicable) criteria.
  
We will detail the respective output files that are derived from Simple [Examples](#examples) #5:   


### query.txt
  
    cat query.txt

```
inclusion strategy: mapped
inclusion vocabularies: ICD10CM
inclusion codes: F41
inclusion function: or
exclusion strategy: mapped
exclusion vocabularies: MeSH
exclusion codes: D002998
exclusion function: and
```  

### inclusion_criteria_mapped.txt

     cat inclusion_criteria_mapped.txt
  
```
codes	vocabularies	concept_id	concept_name	domain_id	vocabulary_id	concept_class_id
F41	ICD10CM	1568230	Other anxiety disorders	Condition	ICD10CM	3-char nonbill code
```
  
### inclusion_criteria_mapped_concepts.txt  
  
     head inclusion_criteria_mapped_concepts.txt
  
```
descendant_concept_id	ancestor_concept_id	concept_name	domain_id	vocabulary_id	concept_class_id	concept_code	pt_count
381537	442077	Organic anxiety disorder	Condition	SNOMED	Clinical Finding	17496003	NA
432600	442077	Stress reaction causing mixed disturbance of emotion and conduct	Condition	SNOMED	Clinical Finding	192044009	NA
433178	442077	Anxiety disorder of childhood OR adolescence	Condition	SNOMED	Clinical Finding	109006	NA
434613	442077	Generalized anxiety disorder	Condition	SNOMED	Clinical Finding	21897009	NA
434628	442077	Separation anxiety	Condition	SNOMED	Clinical Finding	126943008	NA
436074	442077	Panic disorder	Condition	SNOMED	Clinical Finding	371631005	NA
436390	442077	Psychogenic rumination	Condition	SNOMED	Clinical Finding	192014006	NA
436676	442077	Posttraumatic stress disorder	Condition	SNOMED	Clinical Finding	47505003	NA
437537	442077	Shyness disorder of childhood	Condition	SNOMED	Clinical Finding	83253003	NA
```
  
### exclusion_criteria_mapped.txt
  
     cat exclusion_criteria_mapped.txt
  
```
codes	vocabularies	concept_id	concept_name	domain_id	vocabulary_id	concept_class_id
D002998	MeSH	45612901	Clonazepam	Drug	MeSH	Main Heading
```

### exclusion_criteria_mapped_concepts.txt  
  
     head exclusion_criteria_mapped_concepts.txt
  
```
descendant_concept_id	ancestor_concept_id	concept_name	domain_id	vocabulary_id	concept_class_id	concept_code	pt_count
798874	798874	Clonazepam	Drug	RxNorm	Ingredient	2598	NA
798875	798874	Clonazepam 0.5 MG Oral Tablet	Drug	RxNorm	Clinical Drug	197527	NA
798876	798874	Clonazepam 1 MG Oral Tablet	Drug	RxNorm	Clinical Drug	197528	NA
798877	798874	Clonazepam 2 MG Oral Tablet	Drug	RxNorm	Clinical Drug	197529	NA
798893	798874	Clonazepam 0.125 MG Oral Tablet [Klonopin]	Drug	RxNorm	Branded Drug	211761	NA
798894	798874	Clonazepam 0.25 MG Oral Tablet [Klonopin]	Drug	RxNorm	Branded Drug	211762	NA
798896	798874	Clonazepam 1 MG/ML Injectable Solution	Drug	RxNorm	Clinical Drug	249943	NA
798897	798874	Clonazepam 0.5 MG	Drug	RxNorm	Clinical Drug Comp	315699	NA
798899	798874	Clonazepam 2 MG	Drug	RxNorm	Clinical Drug Comp	317336	NA
```
  
### outcome.txt
  
     cat outcome.txt

```
# patients found from the inclusion criteria ONLY.
# patients found from the exclusion criteria ONLY.
# overlapping patients excluded from the original inclusion input based on the exclusion criteria.
# patients found that meet the inclusion and exclusion criteria.
```
  
  
### patient_list.txt  
  
     head patient_list.txt 

```
patient_list
1
2
3
```
  
  
## Code Breakdown 
To Do

## Helpful Hints  
* We recommend using the _mapped_ argument for the [findPatients](#findpatients) function because the concepts will not depend on by which format the data was entered (i.e., the _source_concept_). This is important as diffierent institutions may utilize different underlying terminologies, as well as switch primary data entry vocabularies over time (i.e., the switch from ICD-9 to ICD-10). For example, if the user is interested in "Trigeminal neuralgia", using the ICD-10 code "G50.1" with the _direct_ argument, all prior entries that utilized the corresponding ICD-9 code ("350.1") most likely will not be found as many data warehouses do not "back-map" codes. Using the _mapped_ argument will bypass this issue as the standard concept will be used which should capture both options.  

* To ensure complete capture of data concepts of interest, we recommend identifying multiple vocabulary/codes to use using the [Athena](http://athena.ohdsi.org/search-terms/terms) resource. For instance, if interested in finding all individuals taking a Benzodiazepine, consider using both the relevant ATC classes (e.g., N03AE) as well as the relevant Substance (SNOMED) codes (e.g., 16047007). The [exploreConcepts](#exploreconcepts) function can be used to identify and prioiritize which codes are optimal to use.  

* [rec for drug to use rxnorm or atc]

## Team
To Do

## Contact
For questions, comments, errors, bug reports, or issues, please contact: benjamin.glicksberg@ucsf.edu  
For general correspondance, please contact: atul.butte@ucsf.edu
